#!/bin/bash
defaults write ~/Library/Preferences/org.w0lf.vpk autoCheck 1
defaults write ~/Library/Preferences/org.w0lf.vpk autoInstall 0
# defaults write ~/Library/Preferences/org.w0lf.vpk lastVersion 0
defaults write ~/Library/Preferences/org.w0lf.vpk lastupdateCheck 0
osascript -e 'tell application "vpk" to activate'
